USE [Library Management System]

CREATE TABLE Information (
	INFO_ID INT PRIMARY KEY NOT NULL,
	USER_ID INT FOREIGN KEY REFERENCES USERS(USER_ID),
	BOOK_ID INT FOREIGN KEY REFERENCES BOOKS([BooK ID]),
	/*
		Info_ID, User_ID, Book_ID
	*/
)