USE [Library Management System]

CREATE TABLE Student (
		STUDENT_ID INT PRIMARY KEY,
		STUDENT_NAME VARCHAR(20),
		STUDENT_AGE INT,
		STUDENT_CNIC VARCHAR(15) UNIQUE,
		STUDENT_MEMBERSHIP INT FOREIGN KEY REFERENCES MEMBERSHIP(ID),
		STUDENT_PHONE_NO VARCHAR(13),
		PICTURE_PATH VARCHAR(30),
	/*
	
		Student_ID, Name, Age, CNIC, Membership, Phone_Number, Picture_Path
	*/
)