USE [Library Management System]

CREATE TABLE Teacher (
		TEACHER_ID INT PRIMARY KEY,
		TEACHER_NAME VARCHAR(30),
		TEACHER_AGE INT,
		TEACHER_CNIC VARCHAR(15) UNIQUE,
		TEACHER_MEMBERSHIP_ID INT FOREIGN KEY REFERENCES MEMBERSHIP(ID),
		TEACHER_PHONE_NO VARCHAR(13),
		PICTURE_PATH VARCHAR(20),

	/*
		Teacher_ID, Name, Age, CNIC, Membership, Phone_Number, Picture_Path
	*/
)